# https://www.mkdocs.org/user-guide/configuration/
site_name: EFH Planung
site_description: 
site_author: MH
repo_url: https://github.com/8ear/efh/
edit_uri: edit/main/docs/
nav:
  - Home: index.md
  - About: about.md
  - 'FLB Rohbau + Dach': flb_rohbau_dach.md
  - 'FLB Heizung + Sanitär': flb_heizung_sanitaer.md
  - 'FLB Elektro': flb_elektro.md
  - 'FLB Putz + Malerarbeiten': flb_putz_maler.md
  - 'FLB Fenster + Haustür': flb_fenster_haustuer
  - 'FLB Innentüren': flb_innentueren.md
  - 'FLB Garagentor': flb_garagentor.md
theme:
  #name: material
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
  features:
    - search.share
    - search.highlight
    - search.suggest
plugins:
  - search
  - pdf-export:
      verbose: true
      media_type: print
      enabled_if_env: ENABLE_PDF_EXPORT
  - git-revision-date-localized:
      # https://timvink.github.io/mkdocs-git-revision-date-localized-plugin/options/
      fallback_to_build_date: false
      timezone: Europe/Berlin
      type: iso_date
  # https://squidfunk.github.io/mkdocs-material/plugins/optimize/
  - optimize
  - tags:
      tags_file: tags.md
extra_css:
  - css/pdf-export.css
