plugins:
  - search
  - pdf-export:
        verbose: true
        media_type: print
        enabled_if_env: ENABLE_PDF_EXPORT
  - git-revision-date-localized:
      fallback_to_build_date: false
      type: timeago
extra_css:
  - css/pdf-export.css
